---
title: "Bootstrapping-Group-Presentation"
format: revealjs
editor: visual
---

## Introduction
-Resampling is the process of creating new samples based on an observed sample to
gather more information about either the sample or the population the sample
came from. 
-Resampling techniques like permutation tests, cross validation, and 
the jackknife have been prevalent in the statistics world for a while. 
Resampling can come in handy when it's either impossible or unfeasible to 
retrieve a sample from the entire population. 
-With resampling techniques you could verify the accuracy of
the original sample, or make observations about the entire population of
concert goers.
-All of the resampling techniques listed either have assumptions required for
them to make meaningful results, fail at specific estimations, or produce 
errors during the process. 
-The Bootstrap method was introduced to overcome
some of the pitfalls of the jackknife resampling method.

## Bullets

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
